import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Personal Finance",
  description: "Generated by zelgfx",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}

// 1660px
